### ISSUE TITLE
[Issue]: Kill command often fails

### ISSUE THREAD

**Issue by SiverDX** [nanite/ToolKit#8]
### Minecraft Version

1.19.2

### Modloader

43.3.0

### Mod version

2.3.8-build.18+mc1.19.2

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

N/A

### Steps to reproduce the issue

1. Use `/tk kill all`

### Description of the issue you are having

![image](https://github.com/nanite/ToolKit/assets/22003703/ea8143fd-b94a-4d8d-b11c-2ba2d92cbb62)

```log
[14:44:17] [Server thread/ERROR] [minecraft/Commands]: Command exception: /tk kill all
java.lang.ArrayIndexOutOfBoundsException: Index 773 out of bounds for length 513
	at it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap$MapIterator.nextEntry(Int2ObjectLinkedOpenHashMap.java:1236) ~[fastutil-8.5.6.jar%23128!/:?] {}
	at it.unimi.dsi.fastutil.ints.Int2ObjectLinkedOpenHashMap$ValueIterator.next(Int2ObjectLinkedOpenHashMap.java:1737) ~[fastutil-8.5.6.jar%23128!/:?] {}
	at com.google.common.collect.Iterators$1.next(Iterators.java:146) ~[guava-31.0.1-jre.jar%23116!/:?] {}
	at com.sunekaer.toolkit.commands.CommandKill.yeetEntities(CommandKill.java:124) ~[ToolKit-forge-2.3.8-build.18+mc1.19.2.jar%23826!/:?] {re:classloading}
	at com.sunekaer.toolkit.commands.CommandKill.kill(CommandKill.java:105) ~[ToolKit-forge-2.3.8-build.18+mc1.19.2.jar%23826!/:?] {re:classloading}
	at com.sunekaer.toolkit.commands.CommandKill.lambda$register$1(CommandKill.java:72) ~[ToolKit-forge-2.3.8-build.18+mc1.19.2.jar%23826!/:?] {re:classloading}
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:263) ~[brigadier-1.0.18.jar%23120!/:?] {re:mixin}
	at net.minecraft.commands.Commands.m_242674_(Commands.java:240) ~[client-1.19.2-20220805.130853-srg.jar%23869!/:?] {re:mixin,re:classloading,pl:mixin:APP:cupboard.mixins.json:CommandExceptionLoggingMixin,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_242600_(ServerGamePacketListenerImpl.java:1239) ~[client-1.19.2-20220805.130853-srg.jar%23869!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$12(ServerGamePacketListenerImpl.java:1217) ~[client-1.19.2-20220805.130853-srg.jar%23869!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18693_(BlockableEventLoop.java:68) ~[client-1.19.2-20220805.130853-srg.jar%23869!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[?:?] {}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.19.2-20220805.130853-srg.jar%23869!/:?] {re:mixin,re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23869!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23869!/:?] {re:computing_frames,re:mixin,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[client-1.19.2-20220805.130853-srg.jar%23869!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23869!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23869!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[client-1.19.2-20220805.130853-srg.jar%23869!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[client-1.19.2-20220805.130853-srg.jar%23869!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23869!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[client-1.19.2-20220805.130853-srg.jar%23869!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23869!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23869!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:A}
	at java.lang.Thread.run(Unknown Source) [?:?] {re:mixin}
```

### Information

- [X] I have provided as much information as possible

**Comment by MichaelHillcox** [comment]
https://cdn.nanite.dev/data/mods/tk/ToolKit-fabric-2.3.8+test-build-build.9999+mc1.19.2.jar
https://cdn.nanite.dev/data/mods/tk/ToolKit-forge-2.3.8+test-build-build.9999+mc1.19.2.jar

Can you try this build and let me know if the issue has been resolved?

**Comment by SiverDX** [comment]
```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied.</Message>
<Key>
mods/tk/ToolKit-forge-2.3.8+test-build-build.9999+mc1.19.2.jar
</Key>
<BucketName>data</BucketName>
<Resource>
/data/mods/tk/ToolKit-forge-2.3.8+test-build-build.9999+mc1.19.2.jar
</Resource>
<RequestId>17941CE409F18480</RequestId>
<HostId>6d995bd6-76cd-49d4-a84f-e2ab13839e69</HostId>
</Error>
```

**Comment by MichaelHillcox** [comment]
Damn it! Sorry, try now

**Comment by SiverDX** [comment]
Seems fixed
Tried it multiple times, didn't run into the problem
(Usually it would've occured a couple of times already)

**Comment by MichaelHillcox** [comment]
Awesome! :D I'll ship that update
